export const WEBSITES_QUERY_KEY = 'WEBSITES_QUERY_KEY';
export const CAMPAIGNS_QUERY_KEY = 'CAMPAIGNS_QUERY_KEY';
export const GET_CAMPAIGN_QUERY_KEY = 'CAMPAIGNS_QUERY_KEY';
export const GET_WEBSITE_BY_ID_QUERY_KEY = 'GET_WEBSITE_BY_ID_QUERY_KEY';
export const GET_LANGUAGES_QUERY_KEY = 'GET_LANGUAGES_QUERY_KEY';
export const GET_AVAILABLE_TEMPLATES_QUERY_KEY = 'GET_AVAILABLE_TEMPLATES_QUERY_KEY';
export const GET_TEMPLATE_QUERY_KEY = 'GET_TEMPLATE_QUERY_KEY';
